---
# tasks file for php56
- name: INSTALL PACKAGE
  pkgng: name={{ item }} state=present
  with_items:
      - php56
      - php56-mysql
  tags: 
   - install 
   - php 

- name: COPY TEMPLATE php-fpm.conf
  sudo: yes
  template: 
   backup: yes
   src: php-fpm.conf.j2
   dest: "{{ php_fpm_conf_dir }}php-fpm.conf"
   owner: root 
   group: wheel 
   mode:  0420
  tags: 
   - config 
   - php

- name: COPY TEMPLATE php.ini 
  sudo: yes
  template: 
   backup: yes
   src: php.ini-production.j2
   dest: "{{ php_conf_dir }}php.ini"
   owner: root 
   group: wheel 
   mode:  0420
  tags: 
   - config 
   - php



- name: ENABLE php-fpm into rc.conf.
  sudo: yes
  shell: sysrc php_fpm_enable=YES  
  notify: 
    - start php_fpm
  tags: 
   - config 
   - php